#!/bin/bash

set -o pipefail

# git branch to consider for puppet
BRANCH=master

# extra options passed to puppet agent
PUPPET_OPTIONS=

full_puppet_options="$PUPPET_OPTIONS $(git config puppet-receiver.args)"

MODULEPATH="modules"
		

# --- Command line
refname="$1"
oldrev="$2"
newrev="$3"

# --- Safety check
if [ -z "$GIT_DIR" ] ; then
	echo "Don't run this script from the command line." >&2
	echo " (if you want, you could supply GIT_DIR then run" >&2
	echo "  $0 <ref> <oldrev> <newrev>)" >&2
	exit 1
fi

if [ -z "$refname" -o -z "$oldrev" -o -z "$newrev" ] ; then
	echo "Usage: $0 <ref> <oldrev> <newrev>" >&2
	exit 1
fi

if [ "$refname" != "refs/heads/$BRANCH" ] ; then
		exit 0
fi

if ! which puppet >/dev/null ; then
		echo "*** Cannot find puppet"
		exit 1
fi

if ! which facter >/dev/null ; then
		echo "*** Cannot find facter utility"
		exit 1
fi

puppetver=$(facter puppetversion)

if [[ $puppetver == 2.6.* || $puppetver == 0.2* ]] ; then
		validate_command="xargs -n1 puppet --parseonly"
else
		validate_command="xargs puppet parser validate"
fi

DEST=$(mktemp -d --suffix=.puppet-git-receiver)

if ! git archive --format=tar $newrev | (cd $DEST && tar xf -) ; then
		echo "*** Encountered a problem extracting the incoming git tree $newrev" >&2
		rm -rf $DEST
		exit 1
fi

skip_validation=$(git config --bool puppet-receiver.skip-validation)

if [ "$skip_validation" == "true" ] ; then
		echo "*** Skipping puppet validation due to config option puppet-receiver.skip-validation" >&2
else
		echo "*** Validating puppet manifests for $refname" >&2
		# FIXME: what if no pp files?
		if ! find $DEST -name "*.pp" | $validate_command |& sed -u "s,$DEST/,,g" ; then
				echo "*** Encountered a problem validating the puppet manifests" >&2
				rm -rf $DEST
				exit 1
		fi
fi

echo "*** Applying puppet manifests" >&2

# TODO: find appropriate file to apply
sudo puppet apply $full_puppet_options --detailed-exitcodes --modulepath="$DEST/$MODULEPATH" "$DEST/manifests/site.pp" |& sed -u "s,$DEST/,,g"
PUPRET=$?
if ! [ $PUPRET -eq 0 -o $PUPRET -eq 2 ] ; then
		echo "*** Encountered a problem applying the puppet manifest, rejecting update" >&2
		rm -rf $DEST
		exit 1
fi

echo "*** Puppet manifests applied successfully" >&2
rm -rf $DEST
exit 0
