Document: puppet-git-receiver
Title: Debian puppet-git-receiver Manual
Author: <insert document author here>
Abstract: This manual describes what puppet-git-receiver is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/puppet-git-receiver/puppet-git-receiver.sgml.gz

Format: postscript
Files: /usr/share/doc/puppet-git-receiver/puppet-git-receiver.ps.gz

Format: text
Files: /usr/share/doc/puppet-git-receiver/puppet-git-receiver.text.gz

Format: HTML
Index: /usr/share/doc/puppet-git-receiver/html/index.html
Files: /usr/share/doc/puppet-git-receiver/html/*.html
